# This is a basic workflow to help you get started with Actions

name: Upload files to S3

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Run S3-Sync to upload files to S3
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks
      env:
        AWS_S3_BUCKET: 'csevigny'
        AWS_ACCESS_KEY_ID: 'ASIAZVFSM2ZE6LHJOEPB'
        AWS_SECRET_ACCESS_KEY: '9Z+VtPmmWrRiC7xy8adB04Ey/QxfVqWXLY8AxkOd'
        AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
        DEST_DIR: 'RIFF/TestDirectory'      # optional: defaultsroot of the bucket
